basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings #import settings to use the media settings we created 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')), #namespace will allow us to access our urls in a easier way later down the line
    #include will have the CORE app check the STORE app for the urls file 
    path('basket/', include('basket.urls', namespace='basket'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views #we need to connect the urls folder to the views folder.  The . is refering to the STORE folder since that is the folder the urls are in.

app_name = 'store' #app_name is matching the namespace path in the CORE urls folder

urlpatterns = [
    path('', views.product_all, name='product_all'),  #need to connect this path to the view
    path('<slug:slug>', views.product_detail, name='product_detail'), #need to connect this path to the view
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
            # import reverse is a tool that allows us to build urls 

# Creating Tables for our data base.  We will have a category table and a products table

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)
        
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True) #unique=True means we can only have one category of that name
    # slug allows use to search the category on the browser.  It will be something like https/127.01.01:8000/slug/slug
    
    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])
    
    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png') #we are not storing images in the database.  We are storing the link to the image which is held in another folder
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug]) #args is argument that we are passing in
        # store comes from app_name = 'store' and product_details comes from the path (name='product_detail' ) from the urls.py file 
    

    def __str__(self):
        return self.title

basket/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse

from store.models import Product
from .basket import Basket


# Create your views here.

def basket_summary(request):
    return render(request, 'store/basket/summary.html')

def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product)
        response = JsonResponse({'test': 'data'})
        return response

store/views.py
from django.shortcuts import get_object_or_404, render 
# get_object_or_404 will either get the object requested and return it or if it can't, it will return 404

from .models import Category, Product

# Create your views here.


def product_all(request): #request is the request the user is making on the web broswer
    # products = Product.objects.all() #this is a query for the database.  Its the same as the SQL query select all 
    # products = Product.objects.filter(is_active=True) #This would pull all objects that are listed as is_active.  (is_active is set in the admin page)
    products = Product.products.all()  #instad, we are going to create a new model manager to pull all products except for the ones that are not active
    return render(request, 'store/home.html', {'products': products}) #this is the template we want to display (store/home.html) and what data we want to display on the template (products)

# we are going to get an individual object from the data base
def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True) #if the item is not in stock, it will not show the item
    return render(request, 'store/products/single.html', {'product':product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category) #using a sql query to filter through all product's category that match the category_slug from the line above
    return render(request, 'store/products/category.html', {'category':category, 'products':products})

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}BookStore{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Library
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "store:product_all" %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <!-- This is a search bar if needed -->
                    <!-- <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form> -->
                    <a type="button" role="button" href="{% url 'basket:basket_summary' %}" class="btn btn-outline-secondary">
                        <div class='d-inline-flex'>#</div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket" viewBox="0 0 16 16">
                            <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1v4.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 13.5V9a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h1.217L5.07 1.243a.5.5 0 0 1 .686-.172zM2 9v4.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V9H2zM1 7v1h14V7H1zm3 3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 4 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 6 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 8 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5z"/>
                        </svg>
                        basket
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>
</body>

</html>

templates/store/basket/summary.html
{% extends "../base.html" %} 
<!-- since we created a new folder in templates ../ means it needs to go back two folders to find the base.html file -->
{% load static %}
{% block title %}Basket Summary{% endblock %}


{% block content %}
    
    Basket Page

{% endblock%}

templates/store/home.html
<!-- This will import the block from the base.html page -->
{% extends "./base.html" %}
{% load static %}
{% block title %}BookStore{% endblock %}
<!-- This will change the title of the page to Home instead of My Shop was its in the base.html  -->

{% block content %}
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-3">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="h1 fw-bold">Search, Read, Buy, Review</h1>
                <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator,
                    etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
                <p>
                    <a href="#" class="btn btn-primary my-2">Make an account</a>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="pb-3 h5">All Books</div>

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {% for product in products %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                            <div class="card-body">
                                <p class="card-text">
                                    <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <small class="text-muted">9min read</small>
                                    </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    
    
    </main>
{% endblock %}

templates/store/products/category.html
<!-- This will import the block from the base.html page -->
{% extends "../base.html" %}
{% load static %}
{% block title %}
{% if category %}{{category.name}}{% else %}Products{% endif %}
<!-- This will change the title of the page to Home instead of My Shop was its in the base.html  -->
{% endblock %}
{% block content %}


<main>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="pb-3 h5">{{category.name|title}}</div>

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {% for product in products %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                            <div class="card-body">
                                <p class="card-text">
                                    <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <small class="text-muted">9min read</small>
                                    </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    
    
    </main>
{% endblock %}

templates/store/products/detail.html
{% extends "../base.html" %} 
<!-- since we created a new folder in templates ../ means it needs to go back two folders to find the base.html file -->
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <!-- |slice will limit the product description to 355 characters -->
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end"><button type="button" class="btn btn-secondary btn-sm">Add to basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>
{% endblock %}

templates/store/products/single.html
{% extends "../base.html" %} 
<!-- since we created a new folder in templates ../ means it needs to go back two folders to find the base.html file -->
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}

<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <!-- |slice will limit the product description to 355 characters -->
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">${{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end">
    <button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">Add to basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>

{% comment %} using jquery.  Need to make sure it's script is in the head of base.html {% endcomment %}
<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add"%}',
            // create the url pand views page 
            data: {
                productid: $('#add-button').val(), 
                // this getting the value from the add-button id above.  The value is the product id
                csrfmiddlewaretoken:"{{csrf_token}}",
                action: 'post'
            },
            success: function(json) {
            // The data we get back is in json format
            },
            error: function (xhr, errmsg, err) {}
            // This can be any message
        });
    })

</script>

{% endblock %}